-- Imports
require('impatient')
require('autocmd')
-- require('./config/treesitter-config')
-- require('./config/tokyonight-config')
require('./settings/keybinds')
require('./settings/globals')
require('./settings/options')
require('plugins')
require('mason').setup()
